/**
 * Constants of the MyJDownloader API.
 * API Documentation: https://my.jdownloader.org/developers
 */

// MyJdownloader exception source
export const EXCEPTION_MYJD = "MYJD";
export const EXCEPTION_DEVICE = "DEVICE";

// MyJdownloader exception type
export const EXCEPTION_API_COMMAND_NOT_FOUND = "API_COMMAND_NOT_FOUND";
export const EXCEPTION_API_INTERFACE_NOT_FOUND = "API_INTERFACE_NOT_FOUND";
export const EXCEPTION_AUTH_FAILED = "AUTH_FAILED";
export const EXCEPTION_BAD_PARAMETERS = "BAD_PARAMETERS";
export const EXCEPTION_BAD_REQUEST = "BAD_REQUEST";
export const EXCEPTION_CHALLENGE_FAILED = "CHALLENGE_FAILED";
export const EXCEPTION_EMAIL_FORBIDDEN = "EMAIL_FORBIDDEN";
export const EXCEPTION_EMAIL_INVALID = "EMAIL_INVALID";
export const EXCEPTION_ERROR_EMAIL_NOT_CONFIRMED = "ERROR_EMAIL_NOT_CONFIRMED";
export const EXCEPTION_FAILED = "FAILED";
export const EXCEPTION_FILE_NOT_FOUND = "FILE_NOT_FOUND";
export const EXCEPTION_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const EXCEPTION_MAINTENANCE = "MAINTENANCE";
export const EXCEPTION_METHOD_FORBIDDEN = "METHOD_FORBIDDEN";
export const EXCEPTION_OFFLINE = "OFFLINE";
export const EXCEPTION_OUTDATED = "OUTDATED";
export const EXCEPTION_OVERLOAD = "OVERLOAD";
export const EXCEPTION_SESSION = "SESSION";
export const EXCEPTION_STORAGE_ALREADY_EXISTS = "STORAGE_ALREADY_EXISTS";
export const EXCEPTION_STORAGE_INVALID_KEY = "STORAGE_INVALID_KEY";
export const EXCEPTION_STORAGE_INVALID_STORAGEID = "STORAGE_INVALID_STORAGEID";
export const EXCEPTION_STORAGE_KEY_NOT_FOUND = "STORAGE_KEY_NOT_FOUND";
export const EXCEPTION_STORAGE_LIMIT_REACHED = "STORAGE_LIMIT_REACHED";
export const EXCEPTION_STORAGE_NOT_FOUND = "STORAGE_NOT_FOUND";
export const EXCEPTION_TOKEN_INVALID = "TOKEN_INVALID";
export const EXCEPTION_TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS";
export const EXCEPTION_UNKNOWN = "UNKNOWN";